<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PlaceSeeder extends Seeder
{
    public function run()
    {
        $lugares = [
            [ 'id' => 1, 'name' => 'Parque Nacional Natural Tatamá', 'description' => 'Uno de los parques nacionales más importantes de Colombia, ubicado en la cordillera occidental. Alberga una gran diversidad de flora y fauna, incluyendo especies endémicas. Ideal para ecoturismo, observación de aves y senderismo. El parque cuenta con diferentes pisos térmicos que van desde el bosque húmedo tropical hasta el páramo.', 'location' => 'Pueblo Rico, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.11300423', 'longitude' => '-76.09643012', 'image' => '/imagenes/tatama.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:17:20', ],
            [ 'id' => 2, 'name' => 'Parque Las Araucarias', 'description' => 'Hermoso parque natural conocido por sus impresionantes árboles de araucaria. Ofrece senderos ecológicos, áreas de descanso y la oportunidad de disfrutar de la naturaleza en un ambiente tranquilo. Perfecto para familias y amantes de la naturaleza que buscan un día de relajación y conexión con el medio ambiente.', 'location' => 'Santa Rosa de Cabal, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.86513807', 'longitude' => '-75.62127198', 'image' => '/imagenes/araucarias.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:16:52', ],
            [ 'id' => 3, 'name' => 'Parque Regional Natural Cuchilla de San Juan', 'description' => 'Área protegida que conserva importantes ecosistemas de bosque andino. El parque es hogar de diversas especies de aves y mamíferos. Cuenta con senderos interpretativos que permiten a los visitantes conocer la biodiversidad local mientras disfrutan de paisajes montañosos espectaculares.', 'location' => 'Belén de Umbría, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.18337752', 'longitude' => '-75.93420169', 'image' => '/imagenes/cuchillasanjuan2.webp', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:16:20', ],
            [ 'id' => 4, 'name' => 'Parque Natural Regional Santa Emilia', 'description' => 'Parque regional que protege importantes fuentes hídricas y ecosistemas estratégicos. Ideal para actividades de ecoturismo, investigación y educación ambiental. Los visitantes pueden disfrutar de caminatas, observación de flora y fauna, y aprender sobre la importancia de la conservación de los recursos naturales.', 'location' => 'Belén de Umbría, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.20707000', 'longitude' => '-75.90039321', 'image' => '/imagenes/santaemilia2.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:15:48', ],
            [ 'id' => 5, 'name' => 'Jardín Botánico UTP', 'description' => 'Jardín botánico perteneciente a la Universidad Tecnológica de Pereira, dedicado a la conservación, investigación y educación sobre la flora regional. Cuenta con colecciones de plantas nativas, senderos educativos y espacios para la investigación científica. Es un lugar perfecto para aprender sobre la biodiversidad del Eje Cafetero.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.79032331', 'longitude' => '-75.68913818', 'image' => '/imagenes/jardin.jpeg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:14:37', ],
            [ 'id' => 6, 'name' => 'Jardín Botánico De Marsella', 'description' => 'Hermoso jardín botánico que muestra la riqueza florística de la región. Cuenta con una amplia variedad de especies vegetales organizadas en diferentes secciones temáticas. Ideal para visitantes que buscan conocer la flora local, disfrutar de un ambiente tranquilo y participar en actividades educativas sobre botánica y conservación.', 'location' => 'Marsella, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.93670378', 'longitude' => '-75.73689438', 'image' => '/imagenes/jardinmarsella2.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:14:04', ],
            [ 'id' => 7, 'name' => 'Lago De La Pradera', 'description' => 'Hermoso lago artificial rodeado de naturaleza, ideal para actividades recreativas y deportes acuáticos. El lugar cuenta con áreas de picnic, senderos alrededor del lago y espacios para la pesca deportiva. Es un destino popular para familias que buscan un día de esparcimiento al aire libre en un ambiente tranquilo y seguro.', 'location' => 'La Pradera - Dosquebradas, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.82554091', 'longitude' => '-75.67337966', 'image' => '/imagenes/Lago.jpeg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:13:15', ],
            [ 'id' => 8, 'name' => 'La Laguna Del Otún', 'description' => 'Una de las lagunas más importantes del departamento, ubicada en el Parque Nacional Natural Los Nevados. Es un destino de alta montaña que requiere preparación física, pero ofrece paisajes espectaculares y la oportunidad de observar fauna silvestre. La laguna es fuente de agua para la región y un importante ecosistema de páramo.', 'location' => 'Pereira, Santa Rosa, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.78117998', 'longitude' => '-75.41419413', 'image' => '/imagenes/laguna.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:03:51', ],
            [ 'id' => 9, 'name' => 'Chorros De Don Lolo', 'description' => 'Impresionante cascada natural que forma parte de un complejo turístico en Santa Rosa de Cabal. Los visitantes pueden disfrutar de las aguas termales, la cascada y los hermosos paisajes naturales. El lugar cuenta con infraestructura turística que incluye piscinas termales, restaurantes y áreas de descanso.', 'location' => 'Santa Rosa, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.88679900', 'longitude' => '-75.57931116', 'image' => '/imagenes/lolo-2.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:03:10', ],
            [ 'id' => 10, 'name' => 'Termales de Santa Rosa', 'description' => 'Famosos termales naturales con aguas ricas en minerales que ofrecen propiedades terapéuticas. El complejo cuenta con piscinas de diferentes temperaturas, spa, restaurante y alojamiento. Es uno de los destinos más populares de Risaralda para relajación y bienestar, rodeado de un hermoso paisaje montañoso.', 'location' => 'Santa Rosa, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.85058183', 'longitude' => '-75.54652310', 'image' => '/imagenes/termaales.jpg', 'created_at' => '2025-12-15 01:16:00', 'updated_at' => '2026-02-03 13:02:31', ],
            [ 'id' => 11, 'name' => 'Parque Acuático Consota', 'description' => 'Parque acuático familiar con piscinas, toboganes y áreas recreativas. Ideal para pasar un día divertido en familia, especialmente durante el verano. El parque cuenta con restaurantes, áreas de picnic y espacios verdes para descansar. Es un destino popular para residentes locales y turistas que buscan diversión acuática.', 'location' => 'Pereira - Cerritos, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.79927682', 'longitude' => '-75.80588439', 'image' => '/imagenes/consota.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 12:59:26', ],
            [ 'id' => 12, 'name' => 'Balneario Los Farallones', 'description' => 'Balneario natural en las orillas del río Cauca, perfecto para refrescarse y disfrutar de un día al aire libre. El lugar cuenta con áreas de descanso, restaurantes típicos y espacios para actividades recreativas. Es un destino popular durante los fines de semana y festivos, ideal para familias y grupos de amigos.', 'location' => 'La Virginia, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.90280341', 'longitude' => '-75.88541685', 'image' => '/imagenes/farallones.jpeg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 12:55:42', ],
            [ 'id' => 13, 'name' => 'Cascada Los Frailes', 'description' => 'Hermosa cascada natural accesible a través de un sendero ecológico. El lugar ofrece la oportunidad de disfrutar de la naturaleza, tomar fotografías y refrescarse en las aguas cristalinas. Es un destino ideal para excursionistas y amantes de la naturaleza que buscan una experiencia tranquila y relajante.', 'location' => 'La Florida - Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.73563211', 'longitude' => '-75.56127157', 'image' => '/imagenes/frailes3.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 12:58:16', ],
            [ 'id' => 14, 'name' => 'Río San José', 'description' => 'Río de aguas cristalinas que atraviesa hermosos paisajes naturales. El lugar es ideal para actividades como senderismo, observación de aves y disfrutar de la naturaleza. Los visitantes pueden caminar por senderos que bordean el río y disfrutar de la tranquilidad del ambiente natural.', 'location' => 'Cordillera Central - Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.79202113', 'longitude' => '-75.64569543', 'image' => '/imagenes/sanjose3.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 12:57:22', ],
            [ 'id' => 15, 'name' => 'Alto Del Nudo', 'description' => 'Mirador natural que ofrece vistas panorámicas espectaculares de la ciudad de Pereira y el valle del río Otún. Es un destino popular para amaneceres y atardeceres, ideal para fotografía y contemplación. El lugar cuenta con áreas de descanso y es accesible en vehículo, lo que lo convierte en un destino fácil para todos.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.86824202', 'longitude' => '-75.71648598', 'image' => '/imagenes/nudo.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:12:07', ],
            [ 'id' => 16, 'name' => 'Alto Del Toro', 'description' => 'Otro importante mirador de la región que ofrece vistas impresionantes del paisaje cafetero. El lugar es ideal para actividades como parapente, fotografía y simplemente disfrutar de la naturaleza. Cuenta con infraestructura básica y es un punto de referencia para los amantes de los deportes extremos y la fotografía de paisajes.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.80492517', 'longitude' => '-75.63930948', 'image' => '/imagenes/toro.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:11:33', ],
            [ 'id' => 17, 'name' => 'La Divisa De Don Juan', 'description' => 'Mirador y punto de referencia histórico en la vía hacia Altagracia. El lugar ofrece vistas del valle y es un punto de parada común para los viajeros. Cuenta con restaurantes típicos donde los visitantes pueden disfrutar de la gastronomía local mientras admiran el paisaje.', 'location' => 'Vía Altagracia, Altagracia, Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.75434623', 'longitude' => '-75.71491035', 'image' => '/imagenes/divisa.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:10:53', ],
            [ 'id' => 18, 'name' => 'Cerro Batero', 'description' => 'Cerro emblemático del municipio de Quinchía que ofrece vistas panorámicas de la región. Es un destino para senderismo y observación de la naturaleza. El cerro tiene importancia cultural y natural, siendo un punto de referencia geográfica y un lugar de interés turístico para quienes visitan el municipio.', 'location' => 'Quinchía, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.36724326', 'longitude' => '-75.69380316', 'image' => '/imagenes/batero.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:10:06', ],
            [ 'id' => 19, 'name' => 'Reserva Forestal La Nona', 'description' => 'Reserva forestal que protege importantes ecosistemas y fuentes hídricas. El lugar es ideal para ecoturismo, investigación y educación ambiental. Los visitantes pueden disfrutar de senderos ecológicos, observación de flora y fauna, y aprender sobre la importancia de la conservación forestal en la región.', 'location' => 'Marsella, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.88678881', 'longitude' => '-75.72223647', 'image' => '/imagenes/lanona.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:09:30', ],
            [ 'id' => 20, 'name' => 'Reserva Natural Cerro Gobia', 'description' => 'Reserva natural que protege importantes ecosistemas de bosque andino. El cerro es hábitat de diversas especies de flora y fauna, algunas endémicas. Es un destino para ecoturismo y observación de aves, con senderos que permiten a los visitantes explorar la biodiversidad mientras disfrutan de paisajes montañosos.', 'location' => 'Quinchía, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.34197567', 'longitude' => '-75.74000629', 'image' => '/imagenes/gobia.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:08:56', ],
            [ 'id' => 21, 'name' => 'Kaukitá Bosque Reserva', 'description' => 'Reserva privada dedicada a la conservación y el ecoturismo. El lugar ofrece senderos ecológicos, áreas de camping y actividades de educación ambiental. Es ideal para grupos que buscan una experiencia de naturaleza y aprendizaje sobre conservación, con guías especializados que comparten conocimientos sobre la biodiversidad local.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.84352170', 'longitude' => '-75.81820419', 'image' => '/imagenes/kaukita.jpeg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:08:21', ],
            [ 'id' => 22, 'name' => 'Reserva Natural DMI Agualinda', 'description' => 'Distrito de Manejo Integrado que protege importantes ecosistemas y fuentes hídricas. La reserva es crucial para la conservación del agua en la región y alberga una gran diversidad biológica. Es un destino para ecoturismo responsable, investigación científica y educación ambiental, con senderos que permiten conocer la importancia de estos ecosistemas.', 'location' => 'Apía, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.11445906', 'longitude' => '-75.93690656', 'image' => '/imagenes/paisaje2.jpg', 'created_at' => '2025-12-15 01:16:01', 'updated_at' => '2026-02-03 13:07:39', ],
            [ 'id' => 23, 'name' => 'Voladero El Zarzo', 'description' => 'El Voladero El Zarzo, ubicado en la vereda El Jazmín del municipio de Apía, Risaralda, es uno de los destinos más reconocidos para el parapentismo en el Eje Cafetero. Ofrece una vista privilegiada del Valle del Risaralda, el Cerro del Tatamá y parte de los departamentos vecinos.', 'location' => 'Apia, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '5.08118199', 'longitude' => '-75.92593730', 'image' => '/imagenes/mirador5.jpg', 'created_at' => '2026-02-10 23:09:41', 'updated_at' => '2026-02-11 20:44:57', ],
            [ 'id' => 24, 'name' => 'Termales de San Vicente', 'description' => 'Termales San Vicente en Santa Rosa de Cabal, Risaralda, es una reserva natural y spa reconocida por sus aguas termales volcánicas de alta mineralización inmersas en bosque de niebla. Ofrece piscinas termales, la mayor piscina de lodo natural del país, spa, hospedaje en cabañas y senderos ecológicos, destacando como un destino de bienestar, relajación y naturaleza en el Eje Cafetero.', 'location' => 'Santa Rosa De Cabal, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.84949390', 'longitude' => '-75.53317876', 'image' => '/imagenes/termales.jpg', 'created_at' => '2026-02-10 23:14:43', 'updated_at' => '2026-02-10 23:14:43', ],
            [ 'id' => 26, 'name' => 'Eco Hotel Paraiso Real', 'description' => 'El Eco Hotel Paraíso Real se encuentra en Dosquebradas, Colombia, y es un destino ideal para quienes buscan un lugar tranquilo y acogedor. Ofrece habitaciones cómodas, una piscina climatizada, un restaurante, un bar y senderos ecológicos para conectar con la naturaleza.', 'location' => 'Dosquebradas,pereira', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.85657125', 'longitude' => '-76.64465646', 'image' => '/imagenes/paisaje4.jpg', 'created_at' => '2026-02-11 01:04:29', 'updated_at' => '2026-02-11 20:45:18', ],
            [ 'id' => 27, 'name' => 'Parque Bioflora En Finca Turística Los Rosales', 'description' => 'Ven y sumérgete en un mundo de mariposas exóticas y hermosas, podrás adentrarte en la granja de mariposas, un santuario natural donde podrás conocer cada uno de sus encantos, colores y belleza, conocer su proceso de crecimiento, para lo cual nos dirigiremos a una finca cafetera, donde se podrá aprovechar todo un conjunto de atractivos como lo es la biodiversidad y el paisaje particular y hermoso que caracteriza a la región.', 'location' => 'Pereira,Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.83460274', 'longitude' => '-75.71343649', 'image' => '/imagenes/parquecafe.jpg', 'created_at' => '2026-02-11 04:34:47', 'updated_at' => '2026-02-11 20:45:39', ],
            [ 'id' => 28, 'name' => 'Bioparque Mariposario Bonita Farm', 'description' => 'Está desarrollado en una finca cafetera, donde se aprovecha toda una serie de atractivos como lo es la biodiversidad y el hermoso y particular paisaje que lo rodea. Uno de sus atractivos es la granja de mariposas que comprende un mariposario, desarrollado sobre arena de playa blanca para recorrerlo con los pies descalzos.', 'location' => 'Pereira,Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.83122342', 'longitude' => '-75.70561705', 'image' => '/imagenes/ukumari.jpg', 'created_at' => '2026-02-11 04:41:28', 'updated_at' => '2026-02-11 20:45:55', ],
            [ 'id' => 29, 'name' => 'Santuario Otún Quimbaya', 'description' => 'El Santuario de Fauna y Flora Otún Quimbaya se encuentra ubicado en la Cordillera Central en la Región Andina de los Andes en Colombia. Su superficie hace parte del departamento de Risaralda. El área del Santuario se caracteriza por una vegetación representativa de la selva húmeda andina.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.72361111', 'longitude' => '-75.57916667', 'image' => '/imagenes/frailes8.webp', 'created_at' => '2026-02-11 05:01:31', 'updated_at' => '2026-02-11 05:01:31', ],
            [ 'id' => 30, 'name' => 'Barbas Bremen', 'description' => 'La reserva natural Barbas Bremen se ubica en el Eje Cafetero, en la zona limítrofe entre los departamentos de Risaralda y Quindío. Es un área protegida reconocida por sus bosques de niebla y el avistamiento de monos aulladores.', 'location' => 'Pereira, Risaralda', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.69869680', 'longitude' => '-75.65466642', 'image' => '/imagenes/frailes7.webp', 'created_at' => '2026-02-11 05:08:53', 'updated_at' => '2026-02-11 20:46:09', ],
            [ 'id' => 31, 'name' => 'Piedras marcadas', 'description' => 'Las Piedras Marcadas en Dosquebradas son un conjunto de petroglifos que han sido marcados por tribus descendientes de los Quimbayas, una de las etnias más reconocidas de Colombia que habitaron la región hacia el año 1530.', 'location' => 'Dosquebradas,pereira', 'telefono' => NULL, 'email' => NULL, 'sitio_web' => NULL, 'latitude' => '4.81614435', 'longitude' => '-76.62819588', 'image' => '/imagenes/piedras3.jpg', 'created_at' => '2026-02-17 12:27:24', 'updated_at' => '2026-02-17 12:27:24', ],
        ];
        DB::table('places')->insertOrIgnore($lugares);

        // Asociar categorías a los lugares según el nombre (después de insertar)
        $categorias = \App\Models\Category::all();
        $lugaresDB = \App\Models\Place::all();
        foreach ($lugaresDB as $lugar) {
            $nombre = strtolower($lugar->name);
            $categoriasAsociar = [];
            foreach ($categorias as $categoria) {
                // Puedes personalizar los patrones según tus necesidades
                if (
                    ($categoria->slug == 'parques-y-mas' && preg_match('/parque|jard[ií]n|bot[aá]nico/', $nombre)) ||
                    ($categoria->slug == 'paraisos-acuaticos' && preg_match('/lago|laguna|r[ií]o|cascada|balneario|termales|acu[aá]tico/', $nombre)) ||
                    ($categoria->slug == 'lugares-montanosos' && preg_match('/alto|cerro|reserva|mirador|divisa/', $nombre))
                ) {
                    $categoriasAsociar[] = $categoria->id;
                }
            }
            if (!empty($categoriasAsociar)) {
                $lugar->categories()->sync($categoriasAsociar);
            }
        }
    }
}
